### PR TITLE
Updated Azure_IoT_Central_ESP32.ino bug fix

### PR DESCRIPTION
**Pull request by rmadurawe13**
When the ESP32 disconnects from WiFi and then reconnects, it gets stuck in an infinite azure reconnecting loop

### CODE REVIEW

**Review by danewalton-msft — APPROVED** [review]
Thanks for the fix @rmadurawe13 !

Tried on my device and looks to work.

**Comment by danewalton-msft** [comment]
@rmadurawe13 can you make the same change to the `Azure_IoT_Central_ESP32_AzureIoTKit.ino` file?

https://github.com/Azure/azure-sdk-for-c-arduino/blob/517139d66491f145832971b17e4cfadec3915b46/examples/Azure_IoT_Central_ESP32_AzureIoTKit/Azure_IoT_Central_ESP32_AzureIoTKit.ino#L409

**Comment by rmadurawe13** [comment]
Hi @danewalton. Sure, I'll get on that and let you know when I'm done

**Comment by rmadurawe13** [comment]
@microsoft-github-policy-service agree [company=""]

**Comment by rmadurawe13** [comment]
@microsoft-github-policy-service agree

**Pull request merged**
